[package]
name = "yantm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
winit = "0.25"
x11 = "2.18.1"
display-info = "0.4.1"
xcb = "0.8.2"